import"./assets/header-BYFhdvTp.js";/* empty css                     */import{m as T}from"./assets/modal-B6ENpYm-.js";import{a as u}from"./assets/vendor-DOPN71bB.js";const m="4e64f2e0a197aa7c5d1170773553320c",y=document.querySelector(".list"),$=document.querySelector(".pagination ul");let v={input:"",year:"",isSearch:!1};const o=`<svg class="icon" width="18" height="18">
          <use href="./icons.svg#icon-star-outline"></use>
        </svg>`,d=`<svg class="icon" fill="#F87719" width="18" height="18">
          <use href="./icons.svg#icon-star-half"></use>
        </svg>`,c=`<svg class="icon" fill="#F87719" width="18" height="18">
          <use href="./icons.svg#icon-star"></use>
        </svg>`;let p=1,h=1;const j=async a=>{const e={method:"GET",url:"https://api.themoviedb.org/3/genre/movie/list?language=en",headers:{accept:"application/json",Authorization:"Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMWRkMzEzNDEyYzUzMjQyYTU2Nzc5ZjVjMWIwNWJlNSIsIm5iZiI6MTc1MzY5OTE4OS4xOTcsInN1YiI6IjY4ODc1Mzc1MGU0ODE4YTk5OTUyYjQ0YiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.H565ZjOCGF6NhGwiaRj-BAZ12tadYHWeWDarSsxXtc4"}};try{const r=(await u.request(e)).data.genres;return a.map(i=>{var n;return((n=r.find(g=>i===g.id))==null?void 0:n.name)||"undefined"}).join(" ")}catch{return!1}},F=async(a=1)=>{const e=`https://api.themoviedb.org/3/trending/movie/week?api_key=${m}&language=en-US&page=${a}`;try{const t=await u.get(e);return{filteredData:await Promise.all(t.data.results.map(async s=>({title:s.title||s.name,rating:Math.round(s.vote_average),genreId:await j(s.genre_ids),year:s.release_date||s.first_air_date,id:s.id,image:s.poster_path}))),total_pages:t.data.total_pages}}catch{return!1}},U=async(a,e=null,t)=>{const r=e!==null?`https://api.themoviedb.org/3/search/movie?api_key=${m}&query=${a}&include_adult=false&language=en-US&page=${t}&primary_release_year=${e}`:`https://api.themoviedb.org/3/search/movie?api_key=${m}&query=${a}&include_adult=false&language=en-US&page=${t}`;try{const s=await u.get(r);return{filteredFilms:s.data.results.map(n=>({title:n.title||n.name,rating:Math.round(n.vote_average),genreId:n.genre_ids,year:n.release_date||n.first_air_date,id:n.id,image:n.poster_path})),total_pages:s.data.total_pages}}catch(s){return s.data}},S=a=>{y.innerHTML="";const e=a.map(({id:t,title:r,image:s,year:i,rating:n,genreId:g})=>{console.log(g);const M=i.split("-")[0],L=W(n);return s&&`<li id="${t}" style="background-image: url(https://image.tmdb.org/t/p/w500/${s});background-size: cover;
      background-position: center;
      width: 395px;
      height: 574px;">
          <div class="info">
              <p>${r.toUpperCase()} <span style="color:#B7B7B7">${g} | ${M}</span></p>
              ${L}
          </div>
      </li>`}).join("");y.insertAdjacentHTML("beforeend",e)},_=(a,e)=>{$.innerHTML="";let t="";e>1&&(t+=`<li data-page="${e-1}" class="prev"><</li>`);let r=Math.max(1,e-2),s=Math.min(a,e+2);for(let i=r;i<=s;i++)t+=`<li data-page="${i}" class="${i===e?"active":""}">${i}</li>`;e<a&&(t+=`<li data-page="${e+1}" class="next">></li>`),$.innerHTML=t},k=async(a=1)=>{try{const{filteredData:e,total_pages:t}=await F(a);h=t,p=a,S(e),_(h,p),v={input:"",year:"",isSearch:!1}}catch(e){console.log(e)}},b=async(a,e,t=1)=>{try{const{filteredFilms:r,total_pages:s}=await U(a,e,t);if(h=s,p=t,r.length===0){y.innerHTML='<li class="not-found">OOPS... We are very sorry! We don’t have any results matching your search.</li>',$.innerHTML="";return}return S(r),_(h,p),v={input:a,year:e,isSearch:!0},v}catch(r){console.log(r)}},W=a=>{let e="";switch(a){case 0:e=`${o.repeat(5)}`;break;case 1:e=`${d}${o.repeat(4)}`;break;case 2:e=`${c}${o.repeat(4)}`;break;case 3:e=`${c}${d}${o.repeat(3)}`;break;case 4:e=`${c.repeat(2)}${o.repeat(3)}`;break;case 5:e=`${c.repeat(2)}${d}${o.repeat(2)}`;break;case 6:e=`${c.repeat(3)}${o.repeat(2)}`;break;case 7:e=`${c.repeat(3)}${d}${o}`;break;case 8:e=`${c.repeat(4)}${o}`;break;case 9:e=`${c.repeat(4)}${d}`;break;case 10:e=`${c.repeat(5)}`;break;default:throw new Error("Invalid rating")}return`<div>${e}</div>`},f=document.getElementById("catolog-form"),w=document.querySelector(".list"),I=document.querySelector(".pagination ul"),z="4e64f2e0a197aa7c5d1170773553320c";let l={input:"",year:"",isSearch:!1};f.addEventListener("submit",async a=>{a.preventDefault();const e=a.target.elements.input.value,t=a.target.elements.choose.value;if(e===""){w.innerHTML='<li class="not-found">Please enter a search term.</li>',I.innerHTML="",l={input:"",year:"",isSearch:!1};return}const r=await b(e,t,1);l.isSearch=r.isSearch,l.input=r.input,l.year=r.year,f.reset()});I.addEventListener("click",async a=>{if(a.target.tagName==="LI"&&a.target.dataset.page){const e=Number(a.target.dataset.page);l.isSearch?await b(l.input,l.year,e):await k(e)}});w.addEventListener("click",async a=>{if(a.target.nodeName==="LI"){const e=a.target.id;try{const t=await u.get(`https://api.themoviedb.org/3/movie/${e}?api_key=${z}&language=en-US`);T(t.data)}catch(t){console.log(t)}}});k();
//# sourceMappingURL=catolog.js.map
